### ISSUE TITLE
gloopblocks (keep only essentials)

### ISSUE THREAD

**Issue by ChandlerBing1994** [Craigs-Crew/edgy-dark-ominous-game#10]
Most of these are useless. I propose we only use the dirt materials, and the mossy materials, and do away with everything else.

**Comment by wrynvera** [comment]
I agree, we should incorporate some elements

**Comment by lisacvuk** [comment]
I feel that if we are removing a majority of a mods' nodes, we should seriously consider just remaking the nodes we intend to keep instead as a part of another mod.

**Comment by lumberjackgames** [comment]
i don't like the gloopy action personally. I also don't like the mossy nodes appearance. It's based on cobble which is terrible texture as well...I guess I think as a larger issue, anything we keep here belongs in core nodes and lets not have abms running that swap nodes on players builds please

**Comment by wrynvera** [comment]
The consensus have been reached i think, that gloopblocks should be rewritten and or trashed.
For now ill move it to the rewrite track.
If there's a taker for this, incorporating into another mod, feel free to move this to trash, and start a new issue as per the suggestion.

3 devs, 2 members > 5 approvals
