### ISSUE TITLE
replace nyancat

### ISSUE THREAD

**Issue by ChandlerBing1994** [Craigs-Crew/edgy-dark-ominous-game#11]
Potential copyright issue, however it still adds charm. Should be rewritten a bit to only spawn a special item (trophy, cup) that isn't craftable.

**Comment by wrynvera** [comment]
I agree with the charm.
+1 for a rewrite.

**Comment by lumberjackgames** [comment]
+1 for holy grail item

Details: there is only one. it can't be protected, can't be destroyed, so constantly it is found and lost again :P

**Comment by ChandlerBing1994** [comment]
It could spawn different colored holy grails of different rarity (as far as nyancat rarity goes lol).

Pastel green - most common
Gold - Second most common
Pastel purple - rarest

**Comment by lumberjackgames** [comment]
I think we should continue to discuss what exactly to replace nyancat but renaming the issue based on consensus that we will be replacing nyan cat with some novelty/decorative item

**Comment by wrynvera** [comment]
Further discussion on that can take place on another issue once someone is taking this task, i think here, we are just trying to clarify whether it should be rewritten.

**Comment by bobmacphee** [comment]
I quite like nyancats and don't see a reason to change or remove them, unless they can be changed to make them useful for something else such as crafting special tools etc.

**Comment by lumberjackgames** [comment]
>  don't see a reason

The copyright infringement is the reason, unfortunately. its possible renaming it and slightly altering it (like changing the color) could be all we really need to change.

**Comment by wrynvera** [comment]
#100
