### ISSUE TITLE
Rewrite streets (keep only essentials)

### ISSUE THREAD

**Issue by ChandlerBing1994** [Craigs-Crew/edgy-dark-ominous-game#12]
Some nodes need retexturing/or downscaling to be visually consistent with the rest of the game.

**Comment by lumberjackgames** [comment]
I personally would be okay with not using streets and just having concrete and asphalt as nodes available for road building. I agree, if we are keeping it, definitely needs re-texturing to fit the other textures better. maybe Raven is interest :P?

**Comment by wrynvera** [comment]
Agree with lumber, im okay as well with just having the core nodes.
These nodes should be incorporated into the core "blocks" mod

We can scrap the rest of the mod.

**Comment by lisacvuk** [comment]
Do we even need the asphalt/concrete streets? Are there no better textures we could use to denote roads?

**Comment by ChandlerBing1994** [comment]
I agree with lumber. Keep core nodes (Asphalt, Concrete, Asphalt with dotted lines) scrap the rest of the mod.

**Comment by lumberjackgames** [comment]
> Do we even need the asphalt/concrete streets? Are there no better textures we could use to denote roads?

My only thoughts about this is some people like building contemporary styled buildings and cities, as boring as that is :P

**Comment by wrynvera** [comment]
4 approvals, closing. But, there needs to be further discussion what to keep and what to throw, when someone takes on this task.
Moving to rewrite track and pending track.
