### ISSUE TITLE
From idea to concept to implementation

### ISSUE THREAD

**Issue by wrynvera** [Craigs-Crew/edgy-dark-ominous-game#13]
Accepted ideas (issues) will go into a pending track (displayed here; https://github.com/Craigs-Crew/edgy-dark-ominous-game/projects/2 )

Pending tracks are on hold until someone agrees to takes them up.
If the idea is something that requires more discussion, particular of new features, a new issue will be started by the taker, and upon approval of that, the idea officially goes into the WIP track, until its completion.

If its a simple idea, that the concept of which has already been discussed in the original issue thread, then it progresses straight into WIP, considering that the original proposer is taking it as well.

**Comment by ChandlerBing1994** [comment]
Support.

**Comment by lisacvuk** [comment]
Support

**Comment by wrynvera** [comment]
EDIT: added a concept track to the project, those are for the issues that are taken but doesn't have a solid concept behind it yet. As mention, this will go through another round of vetting, before reaching the WIP track.

**Comment by wrynvera** [comment]
Closing for the same reason as per #2
