### ISSUE TITLE
[WIP] Furniture outline

### ISSUE THREAD

**Issue by lisacvuk** [Craigs-Crew/edgy-dark-ominous-game#14]
This mod should provide an interface for registering it's nodes - other mods should depend on it, and call it.  
Interface idea:  
We have a ```furniture.register_for_base(node_name)``` function, which takes the name of a registered node. It looks it up in ```minetest.registered_nodes```, and determines it's description, groups, and textures. From here, it generates furniture definitions for that base.

Furniture nodes it should feature (please suggest additional ones):
- Beds - #5  
- Chairs
- Benches
- Short tables
- Tall tables
- Shelves
- Doors (?)
- Flowerpots
  
More:
- Light emitting decorations
  
  
Problems:  
@theraven262 has suggested custom textures for some furniture nodes. This would need to be another interface which takes in specific texture names, instead of determining them from the node definition.

**Comment by lumberjackgames** [comment]
- wall sconces

**Comment by lumberjackgames** [comment]
also this has been discussed but I will add I suggest using ts_furniture as a base for this mod, just as a simple framework. then we can customize it to do things like let you select groups to register (wood, tree, stone, etc.) and then we could do the custom texture furniture as well

**Comment by lisacvuk** [comment]
> also this has been discussed but I will add I suggest using ts_furniture as a base for this mod, just as a simple framework. then we can customize it to do things like let you select groups to register (wood, tree, stone, etc.) and then we could do the custom texture furniture as well

ts_furniture doesn't have many node types defined, and it implements some functionality (sitting, namely) which I feel we don't need. I'm leaning towards a full rewrite, and would be very interested in taking it on myself.

**Comment by lumberjackgames** [comment]
can we merge chests and cabinet type storage in this?

**Comment by lumberjackgames** [comment]
> > also this has been discussed but I will add I suggest using ts_furniture as a base for this mod, just as a simple framework. then we can customize it to do things like let you select groups to register (wood, tree, stone, etc.) and then we could do the custom texture furniture as well
> 
> ts_furniture doesn't have many node types defined, and it implements some functionality (sitting, namely) which I feel we don't need. I'm leaning towards a full rewrite, and would be very interested in taking it on myself.

Sitting is fun for screen shots. I have implemented basic cabinets and 3d ladders in nodebox definitions if you are interested:
https://github.com/mt-frontier/mt-frontier/blob/master/mods/ts_furniture/init.lua
The cabinet mechanics is wonky but it can be easily fixed.

**Comment by lumberjackgames** [comment]
Doors and trapdoors as well

**Comment by theraven262** [comment]
I would withdraw that recommendation for node-specific textures, at least for now, I don't think it is necessary.

**Comment by wrynvera** [comment]
There should be a consideration to convert complex nodeboxes into meshblocks, those will better performance wise, and cleaner.
