### ISSUE TITLE
Rewrite farming

### ISSUE THREAD

**Issue by ChandlerBing1994** [Craigs-Crew/edgy-dark-ominous-game#15]
Should be expanded a bit as I don't feel like farming reaches its true potential. With the current farming system you can only really make haystacks and wool, and even then it's very limited in the amount you can produce.

**Comment by lisacvuk** [comment]
Farming creates a lot of lag, and doesn't have much use without a hunger mod imo. Do we really need it?

**Comment by lumberjackgames** [comment]
I would like ornamental  farming/gardening blocks more than farming specifically.

**Comment by wrynvera** [comment]
+1 for ornamental farming/gardening
I think its worthwhile reconsidering the purpose of farming, as lisac said, it's essentially useless without a hunger mod, apart from the occasional heals from fall damage.
Crops should be rewritten to have a more meaningful purpose, much like how cactus farming was on craigs.

Additionally, whoever takes this task should consider converting all abms/lbms to node timers, that stops running when the crops are fully grown etc.

**Comment by bobmacphee** [comment]
I've always been a fan of farming as a source of materials such as wool and straw. I definitely agree with @neinwhal that they should be made more useful, for example being able to use cactus as fuel. This also encourages a form of economy as materials that are hard/slow to farm can be sold for a profit.

**Comment by wrynvera** [comment]
4 approvals for the rewrite. Closing issue, moving this to pending track.
