### ISSUE TITLE
Rewrite colouredstonebricks (Keep/improve aesthetics)

### ISSUE THREAD

**Issue by ChandlerBing1994** [Craigs-Crew/edgy-dark-ominous-game#16]
Keep the exact textures but probably merge it with a similar mod with better functionality.

**Comment by lisacvuk** [comment]
This can be solved using https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L619 - it would also reduce the media download new players have to make  
@theraven262

**Comment by ChandlerBing1994** [comment]
Sure. As long as they look the same as the regular colouredstonebricks.

**Comment by lumberjackgames** [comment]
we can use this as a boilerplate to accomplish this: https://github.com/kakalak-lumberJack/paintedstone
paintedstone just colorizes the stone bricks and tiles, but we can touch up the current colouredstone textures and make overlay textures to support tile, brick and any other forms we want (if we wanted micro-tiles for example)

**Comment by theraven262** [comment]
Here is one little detail, the original coloured stone bricks were made using a colorized overlay, making them look smoother. We should replicate this because it makes them much more useful when building modern style builds or using them as a replacement for an absent material.

**Comment by wrynvera** [comment]
From experience, I have never gotten colorize nodes to look exactly how I wanted them to.
But if someone takes this on, and can provide an equivalent that uses similar methods, that most of us are pleased with, and reduces the amount of media files, sure, I'm all for it.

Anyone that takes on this task, I would like to see another round of vetting, but I'm ok with the idea behind it.

**Comment by bobmacphee** [comment]
I would agree that it should be rewritten but must look exactly the same as the original.

**Comment by wrynvera** [comment]
4 approvals, closing, moving to pending/rewrite track.
For any tackling this, as proposed above, I would like to see another round of vetting;
The consensus here is the textures should look close or better than the original.
