### ISSUE TITLE
currency

### ISSUE THREAD

**Issue by ChandlerBing1994** [Craigs-Crew/edgy-dark-ominous-game#17]
Is this really needed? We could just use gold bars as the currency.

**Comment by lisacvuk** [comment]
I feel we don't need a currency beyond built-in ores

**Comment by wrynvera** [comment]
Agreed.

**Comment by lumberjackgames** [comment]
I approve. bunch of commies :P

**Comment by wrynvera** [comment]
4 approval, closing and moving to trash.
