### ISSUE TITLE
Remove carts

### ISSUE THREAD

**Issue by ChandlerBing1994** [Craigs-Crew/edgy-dark-ominous-game#18]
Way too laggy, the vast majority of the lag on servers is caused by carts. They only really serve an aesthetic purpose as they aren't faster than running.

**Comment by lisacvuk** [comment]
Yup, remove carts.

**Comment by lumberjackgames** [comment]
I don't care for carts unless they serve some greater function like automating inventory movement across distances or something interesting like that.

**Comment by bobmacphee** [comment]
Unless the lag can be reduced somehow I quite agree that they aren't worth it, especially since they aren't any faster than walking. Would much rather use sprint.

**Comment by wrynvera** [comment]
4 approvals, closing. In the future, i think there might be a possibility of reviving it, and looking in less laggy methods, I do miss craig's railway system. Moving to trash for now.
