### ISSUE TITLE
travelnet (aesthetic change/ rewrite)

### ISSUE THREAD

**Issue by ChandlerBing1994** [Craigs-Crew/edgy-dark-ominous-game#19]
Needs slight retexturing/slight aesthetic change to make it not look so out of place

**Comment by wrynvera** [comment]
I think there might be a potential to expand upon travelnet, if anyone has any ideas.
Otherwise, travelnet by itself have served us well, and I agree, the only change it needs for now is a retexture/aesthetic change.

**Comment by kakalak-lumberJack** [comment]
I think I would rather something less physically obtrusive, like a bus route sign or information booth.

Also it might be nice to make them multi user friendly. Sort of like wifi chest but for travelnets. Users will see a list of available networks and option to save the station to their own network. The networks themselves would be established by players "bookmarking" more than one station.

My main interest is avoiding having any travel type node littering the map.

**Comment by theraven262** [comment]
Perhaps make it a signpost with multiple arrows pointing in different directions, implying it is showing the way around. I think it should be made out of wooden planks, because most of utility nodes in the default game are.

**Comment by bobmacphee** [comment]
I definitely agree that travelnet aesthetics should be changed, the sign post idea is great but I would also like to see an even less obtrusive version such as a pressure-plate or single node version that could be better incorporated into builds.

**Comment by wrynvera** [comment]
4 approvals, closing and moving to pending track.
