### ISSUE TITLE
Making decisions

### ISSUE THREAD

**Issue by wrynvera** [Craigs-Crew/edgy-dark-ominous-game#2]
The first assumption is that we are working with a team of 6 here;
me, lisac, lumber, raven, sg & bob, I'm not sure if luper is officially part of the project?

There's no way we will get 100% approval on every single issue, so this is what I'm proposing;
For an idea to pass, we need at least 2 developers + majority to agree on it.
Developers in this sense, means me, lumber and lisac, because we are the one working on the code, we have the priority of deciding.
Majority refers to the entire team, in this case, majority means we need at least 4 votes total.

So for an idea to pass, we need 2 developers + 2 members to agree with it.

**Comment by lumberjackgames** [comment]
I think we should include Lupercus as a voting member if he is interested and plans to contribute in a testing capacity. He played a lot on Gabos and so far the team is heavily balanced to Craig's regulars :P

**Comment by theraven262** [comment]
I had this feature idea, make multiple types of bricks/tiles for each material block (crafting value 1 to 1), and all of them to be "3D" as this mod does https://forum.minetest.net/viewtopic.php?t=11179&p=176555
Also remove crafting for these and make them craftable in the circular saw

**Comment by ChandlerBing1994** [comment]
I agree.

**Comment by lumberjackgames** [comment]
I think at some point in the future we need to define a process for including new stakeholders' input but for now I think this is fine and I agree.

**Comment by wrynvera** [comment]
To reclarify, the numbers i used in the thread are based off the assumption of current members we have.
The basic rule here is.

Above 50% developers & > 50% members
For the prior, unless we are getting a new modder on the team, for now its fixed to be me, lumber and lisac, so it will always need at least 2 of us to agree onit.
For the members, the numbers seem uncertain now, but it is the total amount of members we have, if we have 6, it will be 4 approvals total (including the dev approvals), if we have 8, it will be 5 total (including the dev)

**Comment by wrynvera** [comment]
Since there's no more comments on this, and considering we have been following this principle, ill close this issue accordingly.
Further changes in the future can be discussed in a new issue as required or through discord.
