### ISSUE TITLE
trash butterflies / fireflies

### ISSUE THREAD

**Issue by ChandlerBing1994** [Craigs-Crew/edgy-dark-ominous-game#20]
Really unnecessary/sort of annoying. They don't add anything new or interesting to the game.

**Comment by theraven262** [comment]
Agreed. I don't remember having them on Craig's anyway, should also reduce lag.

**Comment by lisacvuk** [comment]
Support

**Comment by bobmacphee** [comment]
I don't ever recall having seen such a thing but I imagine they would cause unnecessary lag and aesthetically I don't think they provide much benefit.

**Comment by wrynvera** [comment]
4 approvals, closing and moving to trash.
