### ISSUE TITLE
darkage

### ISSUE THREAD

**Issue by ChandlerBing1994** [Craigs-Crew/edgy-dark-ominous-game#22]
Most of its blocks are actively used, and it textures are fairly visually compatible with the rest of the game. May need some slight tweaks, however.

**Comment by lumberjackgames** [comment]
I think maybe we just salvage what we want for core nodes and bin the rest. I really only want basalt type node, chalk and straw

**Comment by wrynvera** [comment]
Agree, essential elements should be incorporated into core nodes.

**Comment by lisacvuk** [comment]
I don't like how darkage blocks are generated. I would be much more comfortable if they could be crafted from common materials.

**Comment by ChandlerBing1994** [comment]
I use most of the darkage materials, so I would consider them 'essential'.

I'm also not sure if I would support making them craftable from common materials. Maybe just make them appear a bit more frequently

**Comment by wrynvera** [comment]
darkage mapgen is a completely unnecessary cause of lag.
But i disagree with having them craftable from common materials.
I still like having to mine these materials out of the ground.

We can either convert the mapgen to one that is using minetest native oregen, which frankly I'm not sure why darkage doesn't do so.
Or, we can include certain materials as part of biomes generation itself.

**Comment by ChandlerBing1994** [comment]
Is it possible to make them generate through Minetest's native oregen but still have them appear in huge clusters like they normally do?

**Comment by wrynvera** [comment]
Yes very much so.

**Comment by ChandlerBing1994** [comment]
I support that idea, then

**Comment by bobmacphee** [comment]
I agree that we should keep most of the materials, I’ve used most of them at some point and have seen them used a lot in other people’s builds. I also agree with this:

> Is it possible to make them generate through Minetest's native oregen but still have them appear in huge clusters like they normally do?

**Comment by wrynvera** [comment]
General consensus from what I can tell is, keeping most of darkage materials + rework mapgen + remove some useless materials.
In this regard, i think me, @lumberjackgames @bobmacphee @ChandlerBing1994 responses fit within this consensus.
Correct me if I'm wrong, otherwise, will close this in a day and make the appropriate actions.

**Comment by ChandlerBing1994** [comment]
Yup this is correct.

**Comment by theraven262** [comment]
Some graphics need to be redone, such as the wooden support overlay missing a shadow iirc. Apart from fixes such as that I would keep all the stuff looking as it does (except maybe gneiss, but we even found a use for that back on the old server).

**Comment by wrynvera** [comment]
Closing, moving to rewrite/pending.
Whoever works on this, I would like to see another round of vetting to decide which blocks to keep and such.
