### ISSUE TITLE
Incorporate moreores into core ores.

### ISSUE THREAD

**Issue by wrynvera** [Craigs-Crew/edgy-dark-ominous-game#23]
^ per title

**Comment by ChandlerBing1994** [comment]
Support.

**Comment by lumberjackgames** [comment]
Are people wanting mithril for the armor potentially? I'm not sure what moreores adds other than variety for armors.

**Comment by wrynvera** [comment]
Personally, i think i just like the aesthetic.
Considering how rare mithril as well, this could be utilized to create some expensive crafting recipes.

**Comment by lumberjackgames** [comment]
> Personally, i think i just like the aesthetic. Considering how rare mithril as well, this could be utilized to create some expensive crafting recipes. I think the quirk of the mithril being not true to lore color is also a nice throwback to craigs/gabos

Sounds good :+1:

**Comment by lisacvuk** [comment]
I like that moreores block textures fit MT game, so support

**Comment by wrynvera** [comment]
4 approvals, closing, will merge accordingly
