### ISSUE TITLE
trash building_blocks except hardwood

### ISSUE THREAD

**Issue by ChandlerBing1994** [Craigs-Crew/edgy-dark-ominous-game#24]
Does not provide anything unique that the other mods don't already have. Trash completely and keep only the hardwood.

**Comment by lumberjackgames** [comment]
I don't even know what this mod is. I second trashing it :D

**Comment by bobmacphee** [comment]
Agree, let's get rid of it.

**Comment by theraven262** [comment]
As far as I can see this is the mod that had half of its crafting recipes missing, the textures weren't that good anyway. I agree with removing it.

**Comment by lisacvuk** [comment]
No clue what it is, trash it

**Comment by wrynvera** [comment]
Closing, moving to trash
