### ISSUE TITLE
Remove email

### ISSUE THREAD

**Issue by ChandlerBing1994** [Craigs-Crew/edgy-dark-ominous-game#25]
Not really needed anymore. We'll have direct communication through Discord.

**Comment by theraven262** [comment]
I don't remember using this except for a few days after it was added. Discord/IRC replace it and do the job much better, I vote for removal.

**Comment by wrynvera** [comment]
I think there's some value to having some form of ingame offline communication.
That being said, I personally don't like the way email is done, and I'm ok with this being removed for now;
But at some stage, I would like to see a possible rewrite.

**Comment by lisacvuk** [comment]
Support for email remove

**Comment by wrynvera** [comment]
4 approvals. Closing. Moving to trash, but I do hope to see a rewrite at some point, but its very low priority.
