### ISSUE TITLE
[Mod/feature request] Semiprecious

### ISSUE THREAD

**Issue by lumberjackgames** [Craigs-Crew/edgy-dark-ominous-game#26]
[Semiprecious](https://github.com/kakalak-lumberJack/semiprecious)

It may need some rewrite and a texture touch up to fit in, but I would like to see this mod or its nodes in some form as a source of naturally colorful tiles, bricks, furniture as I personally don't like the colouredbrick texture for the styles I tend to build in. It also makes mining a bit more colorful.
[screenshot:](https://github.com/kakalak-lumberJack/semiprecious/blob/master/semiprecious_nodes.png)

**Comment by theraven262** [comment]
I would like this mod to be added, also I can edit the textures to fit into the style.

**Comment by ChandlerBing1994** [comment]
I support it being added as long as raven edits the textures to match the vanilla Minetest style.

**Comment by lisacvuk** [comment]
Likewise, it would be really fun to have lots of different gem blocks for decoration

**Comment by theraven262** [comment]
@lumberjackgames The blocks from this mod should also have tile variations as other base blocks do, I'm making those textures aswell.

**Comment by wrynvera** [comment]
Closing this because a pull is already created, move further discussions there.
