### ISSUE TITLE
[Feature request] SFINV trash slot

### ISSUE THREAD

**Issue by lumberjackgames** [Craigs-Crew/edgy-dark-ominous-game#27]
Trash can in the crafting grid window similar to what creative inventory has. [Here's an example mod](https://github.com/kakalak-lumberJack/sfinv_trash). It is a bit more mobile friendly than /pulverize as well.

**Comment by lisacvuk** [comment]
IMO needing a trash slot is a consequence of bad design: players shouldn't feel the need to delete items. This should be solved by the ability to reverse recipes.

**Comment by ChandlerBing1994** [comment]
Maybe a backpack mod should be added as well. 99% of the times I've needed to trash items it's been due to my inventory being full after a mining expedition.

**Comment by lumberjackgames** [comment]
> IMO needing a trash slot is a consequence of bad design

I agree to a certain extent, but some issues are tricky to design around, for example. Say I am mining, accumulating way more cobble than I need because I am mainly trying to get ores for tools or something; Sometimes, as a player, trashing a stack or two of cobble to avoid having to go store it and make my way back to a place in the mine is a choice I would make. 

Same with epic building requiring lots of landscaping. You end up accumulating dirt, grass, flowers, etc. Sometimes you just end up with too much of common items that aren't worth storing. I don't think we can design around some items like this, because they do serve a aesthetic purpose in the map, but as inventory items they are junk or just accumulate much faster than they are needed.

A trash slot addresses these types of problems with very little code code/resource cost and will help avoid players throwing stacks out on the ground and leaving them to take up server resources being rendered as item entities until they get garbage collected. I think that really is the main benefit from a server implementation point which I neglected to mention up front.

**Comment by lumberjackgames** [comment]
> Maybe a backpack mod should be added as well. 99% of the times I've needed to trash items it's been due to my inventory being full after a mining expedition.

This could probably be a separate issue for discussion. Bags/backpacks would probably be pretty useful in this game.

**Comment by lumberjackgames** [comment]
Will reopen issue if needed after server launch.
