### ISSUE TITLE
bucket -- needs mechanism to prevent or reduce greifing

### ISSUE THREAD

**Issue by lumberjackgames** [Craigs-Crew/edgy-dark-ominous-game#28]
Buckets should have a mechanism to reduce instances of water/lava griefing. I don't want to spend my time cleaning up messes and policing things like this that could be prevented programmatically :)

**Comment by wrynvera** [comment]
I think the main issue is really, there's no good mechanism for managing this.
As least as far as i can think of.
But if anyone can come up with one, please do.

**Comment by kakalak-lumberJack** [comment]
This could be handled better as a server implementation issue anyway, I guess.

**Comment by lumberjackgames** [comment]
Closing this as a non-game issue (belongs in server administration discussion)
