### ISSUE TITLE
sban and other server implementation mods belong in separate repo?

### ISSUE THREAD

**Issue by lumberjackgames** [Craigs-Crew/edgy-dark-ominous-game#3]
Should we exclude mods not directly related to gameplay (related to server administration such as sban) from server implementation details (maybe a separate modpack for suggested admin mods)? Feel like this should be left to server admins to sort out to keep things flexible.

**Comment by wrynvera** [comment]
i think this is a worthwhile suggestion

**Comment by wrynvera** [comment]
Closing as per #44 
Can be reopen later.
