### ISSUE TITLE
Freeze/postpone weather

### ISSUE THREAD

**Issue by ChandlerBing1994** [Craigs-Crew/edgy-dark-ominous-game#32]
I suggest replacing the weather mod with another one, namely this one:

https://content.minetest.net/packages/theFox/weather/

**Comment by wrynvera** [comment]
Frankly, im not sure what the minetest_game weather mod does, but a brief look shows that all it does it adjust cloud colours based on biomes, not provide actual weather. Though i never tested it and don't know how much aesthetically it affects things.

I think actual weather would be an amazing addition. That being said, there's no good non-laggy way of implementing it right now. A brief look at the mod shows a couple of lag inducing methods.

I would like to see a rewrite on it, if someone can come up with a good non-laggy way that doesn't heavily involves particles, abms, globalsteps, entities etc.
That being said, I feel that this is a very low-priority rewrite considering its purely an aesthetic change.

**Comment by ChandlerBing1994** [comment]
We can skip it for now as it is indeed low priority

**Comment by bobmacphee** [comment]
I agree that we should postpone this, I don’t think it’s particularly important right now, and definitely we want to prioritise keeping anything lag inducing to a minimum.

**Comment by wrynvera** [comment]
Since i added a freeze track, i thought i should make that applicable for this as well.
So for there's 3 approvals that is a low priority issue, once it gets one more dev approval, ill move it to the freeze track.

**Comment by wrynvera** [comment]
@theraven262 do you think this has a place in skygen? While rain particles feasibility determined to be further observed, there are already some aspects that can be controlled with skygen (darken skies, color accordingly - sandstorm etc) and more when the fog is exposed in the API

**Comment by theraven262** [comment]
Yeah, skygen already modifies the cloud amount based on the biome's humidity.
MTG weather just modifies the cloud amount as well, though, I don't know what that amount is based on.
Colorizing clouds is doable.
When the fog api is exposed a lot of stuff will be added to skygen, mostly for the underground biomes.
Right now skygen does color the biome fog.

I don't know about the particles, haven't used them yet.

**Comment by wrynvera** [comment]
Yeah particles fall under the to-be experimented with more category as previously noted, so should be considered later when appropriate tests have been made to the large-scale deployment of it. I know some old weather mods already uses particles, but they were also notoriously laggy - but again this is years back, and i haven't really tested its performance recently.

On the other stuff, I was thinking of integrating into the "event" system you were working on?
That system can also respond to the current biome, allowing specification per biome.
But this heavily depends on the fog customisation for it to really become significant enough - i.e. heavy rain flow - low visibility / sand/snowstorm - low visibility with yellow/white fog - so it might be best developed and considered after that.
But if there's interest in the matter, providing a framework for it will be very useful.

**Comment by wrynvera** [comment]
Closing this issue since this is a comestic addition and methods available remains to be tested/non-feasible - if anyone of the devs pick this up, just start a new discussion post on discord.
