### ISSUE TITLE
mapfix

### ISSUE THREAD

**Issue by ChandlerBing1994** [Craigs-Crew/edgy-dark-ominous-game#33]
Keep as is, it's perfect as a quick and easy fix for lighting glitches that occur in the map.

**Comment by lumberjackgames** [comment]
I'm not sure this lighting is a problem any more if we are using Carpathian. I think we can maybe save this in the server administration mod category if that is okay. I don't think it should be a core mod of the game.

**Comment by ChandlerBing1994** [comment]
Sounds good.

**Comment by bobmacphee** [comment]
> I'm not sure this lighting is a problem any more if we are using Carpathian. I think we can maybe save this in the server administration mod category if that is okay. I don't think it should be a core mod of the game.

Agree.

**Comment by wrynvera** [comment]
Closing as per #44 
Can be reopen later.
