### ISSUE TITLE
Improve/rewrite skinsdb

### ISSUE THREAD

**Issue by ChandlerBing1994** [Craigs-Crew/edgy-dark-ominous-game#35]
The version of the mod that Craig's used is fairly bland. Needs more skins to make things more fun. Although I wouldn't be opposed if people wanted to remove it. No strong opinion either way.

**Comment by bobmacphee** [comment]
Agree, it was extremely dull just having a handful of skins, I'd say it was a must.

**Comment by lumberjackgames** [comment]
i'm not sure we need skins as core mod of the game seems a bit more on the side of server implementation to me. I'm not opposed to it either but this can be swapped out/updated later in either case.

**Comment by wrynvera** [comment]
Issue discussion transferred to discord for consistency
