### ISSUE TITLE
Rewrite dungeon_loot

### ISSUE THREAD

**Issue by ChandlerBing1994** [Craigs-Crew/edgy-dark-ominous-game#36]
Was never used on Craig's but I believe it can be rewritten to suit this game's needs better, making it less laggy, and having better/more useful items that can be found in the chests

**Comment by lisacvuk** [comment]
I don't know if we need dungeons at all

**Comment by ChandlerBing1994** [comment]
Just like with nyancat they add a certain level of intrigue and charm to the game, so I'd like to still keep them

**Comment by theraven262** [comment]
I think adding semiprecious' gems to the loot table would be nice, kinda like finding treasure

**Comment by wrynvera** [comment]
I agree that there's a certain charm to them.
Rewriting the loot tables to fit is definitely the best option.

**Comment by bobmacphee** [comment]
It always disappointed me that it wasn't incorporated on Craig's. Although many players enjoyed the building aspect, there were also those who enjoyed exploring/mining/caving so definitely anything we can do to keep them interested is great. I'm sure adding more relevant or useful loot is a no-brainer.

**Comment by lumberjackgames** [comment]
I can take or leave dungeons, personally (another issue but can we get a cobble retexture if we keep them?) but making the loot suit our game (isn't this supported with minetest.conf?) is an easy way to at least make them fun to plunder and it can be turned off with configuration settings so I do approve this, too.

**Comment by ChandlerBing1994** [comment]
No need for a cobble retexture imo. We can make the dungeons stonebricks if we want to.
