### ISSUE TITLE
Freeze wieldview

### ISSUE THREAD

**Issue by ChandlerBing1994** [Craigs-Crew/edgy-dark-ominous-game#37]
I suggest replacing wieldview with WieldView II, as WV2 uses textures instead of entities.

https://forum.minetest.net/viewtopic.php?t=25358

**Comment by lisacvuk** [comment]
If we can clean up the dependencies - there are four, out of which we have only 3d_armor.

**Comment by wrynvera** [comment]
As i stated in discord, the method this mod uses is a mass over-complication of things.
Entities have benefits compared to textures, it can handle a wider variety of appearances.
If we want to switch to textures, however, for a slight improvement in lag reduction, it can be done in less complication means, in conjunct with 3d_armour.

Considering this a very low priority, I would rather keep the current wieldview mod and relook again at it at the later stage.

**Comment by lumberjackgames** [comment]
Agreed with the other devs. We can revisit this in the future but not an essential improvement right now.

**Comment by wrynvera** [comment]
minor non-essential improvement, to be reconsidered when/if working on the player model.
