### ISSUE TITLE
Replacer: lumberJack's version of the mod

### ISSUE THREAD

**Issue by lisacvuk** [Craigs-Crew/edgy-dark-ominous-game#4]
https://github.com/kakalak-lumberJack/replacer  
  
It has some QOL features (namely no chat spam) so I would consider it better than vanilla one

**Comment by lumberjackgames** [comment]
WE have two options. 1) A version already added to craigs with the same keys as original that moves notifications to a hud below weildhand (out of chat)
2) A version with the above feature AND adds a painting-like mechanic to placing nodes (hold down and place in row, for example), but I had to re-engineer the key strokes to make this work. See the repo linked in the issue.

**Comment by wrynvera** [comment]
Im ok with both, but eitherways, I want replacer to incorporated into the tools mod as an essential basic tool.
Using the replacer has a been a major part of my building journey, and I'm sure most of you as well.

**Comment by ChandlerBing1994** [comment]
I'm for option 2.

**Comment by lumberjackgames** [comment]
When i revisit the mod to add it, i may even be able to give it a per player setting so that people can have the old config or the new one with a command or something.

**Comment by bobmacphee** [comment]
I’d be happy with either of the aforementioned options but would lean more to option 2, of course if you could set it either way that would be even better. 
In regards to the texture change to gabo’s wand as proposed by lumberJ on discord I would approve of this also.

**Comment by lumberjackgames** [comment]
It looks like everyone pretty much wants option two and I should be able to implement options for both. Closing this issue and moving to WIP!
