### ISSUE TITLE
Trash unifieddyes

### ISSUE THREAD

**Issue by wrynvera** [Craigs-Crew/edgy-dark-ominous-game#43]
I feel that unifieddyes just overcomplicates the crafting process without any good reason.
The default dye mod provides enough colours, we don't need to delve into the entire colour spectrum.

**Comment by ChandlerBing1994** [comment]
Was going to suggest that. Support.

**Comment by bobmacphee** [comment]
I agree with this, it’s an unnecessary complication.

**Comment by theraven262** [comment]
Didn't add anything into the game except, sometimes, ways to convert multiple useless colours into the one you're looking for. It just overcomplicated things imo

**Comment by lumberjackgames** [comment]
Support. I think default dyes was more limited when Craig's was originally built and unified dyes is no longer needed. It looks like this meets the criteria to close this issue and update the projects board to reflect unified dyes being trashed.
