### ISSUE TITLE
Pause discussion of server-maintenance/management mods

### ISSUE THREAD

**Issue by wrynvera** [Craigs-Crew/edgy-dark-ominous-game#44]
A more lenient followup to #3 
craig's server game includes a couple of these mods; namely
- mapfix
- worldedit
- report
- mapserver
- debug
- sban

These mods, for most parts, I believe are solely focused on the idea of server maintenance and management and have little value otherwise.
Given that we have a series of content to settle first and the server isn't running yet; I'm suggesting to freeze the discussion on these mods for now.
They can be unfrozen again when we have most of the content done enough for the server to actually run.

**Comment by ChandlerBing1994** [comment]
Fair enough.

**Comment by bobmacphee** [comment]
Agree, these can be discussed when we are closer to going public.

**Comment by wrynvera** [comment]
4 approvals, have made the necessary adjustments to the affecting issues. (A freeze track has been added to the project)
I'm keeping this up for more discussions if needed.

**Comment by wrynvera** [comment]
Closing this issue.
