### ISSUE TITLE
Scifi themed building mods to include

### ISSUE THREAD

**Issue by lumberjackgames** [Craigs-Crew/edgy-dark-ominous-game#46]
A few possible ideas for mods to include
- simple Tron type realm or just blocks with custom textures like [tronblocks](https://github.com/Novacain/tronblocks/tree/master/textures)
- Raven's [warzone](https://github.com/theraven262/minetest-warzone)
- Foot_on_teh_hill's scifi pack with crafting station for industrial/scifi stuff: [link](https://github.com/foot-on-teh-hill/scifipack)

Other ideas are welcomed of course :)
This issue should result in a short list of mods to consider. We can break the disussion out into new issues per mod as needed.

**Comment by lumberjackgames** [comment]
This isn't necessarily high priority right now unless we want to include some scifi realm or something mapgen related. I don't feel strongly about having this feature but it could be something interesting to break up underground. Just wanted to float this while it was on my mind. Definitely want some scifi themed building materials though!

**Comment by theraven262** [comment]
I would leave this to be added after the server launch, as it could very well be a full update we could release on a later date.

**Comment by lumberjackgames** [comment]
Closing this issue as too general. Will open a more specific issue if needed.
