### ISSUE TITLE
[WIP] Replacer mod

### ISSUE THREAD

**Issue by lumberjackgames** [Craigs-Crew/edgy-dark-ominous-game#48]
This mod will incorporate my version of the replacer as discussed in [issue 4](https://github.com/Craigs-Crew/edgy-dark-ominous-game/issues/4) updated to be included in the game's tools mod.

The updated version of  replacer will have aim to have: 
- paint mode (new default) and legacy mode (old behavior)--Done
- texture update from Gabo's version of the mod
- API function to get/set mode by external UI mods -- Done
- Chat commands to select modes -- Done
- HUD support moved to /core/functions.lua to be available to other mods
- Any other minor updates or reorganization needed to conform to game's mod format.

Player's mode settings will be stored in the player object.

**Comment by lumberjackgames** [comment]
Any issues with including the inspector tool as well?

Also, @neinwhal, @lisacvuk , in organizing the code to fit in the tools mod can I leave the hud support in its own file somewhere (suggestions?) to be used generally as a lib for printing to the HUD below the weildhand (for tools or any times that clicking something might need to trigger a message that would otherwise get dumped in chat)?

**Comment by lumberjackgames** [comment]
Do we want the replacer to be able to replace liquids? I don't think they should dig them, but possibly replace is ok/useful. I believe it had this behavior on Gabo's and probably Craigs's at some point, but I think the mod has been updated or this was custom behavior they added because it no longer does this by default.

**Comment by wrynvera** [comment]
@lumberjackgames close this? Afaik, most of it is already completed.
The only exception now is the bugs and minor improvements and this thread shouldn't be needed anymore.
