### ISSUE TITLE
Trash basic_materials

### ISSUE THREAD

**Issue by ChandlerBing1994** [Craigs-Crew/edgy-dark-ominous-game#49]
https://forum.minetest.net/viewtopic.php?t=21000

Trash completely; not a single one of these were ever used on Craig's, let alone have much functionality.

**Comment by wrynvera** [comment]
This is meant to compliment homedecor, providing various crafting materials.
Since homedecor is no more, yeah, this is a clear trash.

**Comment by lisacvuk** [comment]
Trash trash trash +1

**Comment by theraven262** [comment]
Agreed, trash, its useless.

**Comment by lumberjackgames** [comment]
Trashed
