### ISSUE TITLE
Remove map

### ISSUE THREAD

**Issue by wrynvera** [Craigs-Crew/edgy-dark-ominous-game#51]
The map mod is similar to binoculars in that it adds a mapping tool to access the minimap.
Being a building server, where its essential to visual your builds from every angle, minimap should just be enabled by default, and not require a tool to access it.

**Comment by ChandlerBing1994** [comment]
Agreed, remove it.

**Comment by bobmacphee** [comment]
Quite agree with the removal, no reason why it should be more complicated than it needs to be.

**Comment by lumberjackgames** [comment]
Moved to trash. I'll wait for @neinwhal to close the issue in case anything is pending i am unaware of.
