### ISSUE TITLE
Combine itemframes

### ISSUE THREAD

**Issue by wrynvera** [Craigs-Crew/edgy-dark-ominous-game#52]
Should be apart of the furniture mod #14
Perhaps offering more itemframes/framing designs too.
One that comes to mind is the medieval shop signs.

**Comment by ChandlerBing1994** [comment]
Agreed, combine it with the furniture mod.

**Comment by bobmacphee** [comment]
I agree that it should be combined.

**Comment by wrynvera** [comment]
Approved, moving to pending/combine track
