### ISSUE TITLE
Expand and combine fake_fire

### ISSUE THREAD

**Issue by wrynvera** [Craigs-Crew/edgy-dark-ominous-game#53]
I like to see more options provided
Could be apart of furniture as well #14

But at the very least, it should be combined accordingly at its current stage.

**Comment by ChandlerBing1994** [comment]
IMO regular fire shouldn't exist within the game as it can burn things down. It should be replaced with fake_fire.

**Comment by wrynvera** [comment]
Yeah, regular fire will never be included.
But when i say more options, i refer to more types of fake fire.
Braziers, bonfire etc

**Comment by theraven262** [comment]
The usual fire with its special drawtype is too big to fit inside any brazier of a single node size. If we could map the fire texture to a different model, or a few different models now that we're at it, it would make it much more useful. Custom torches aswell, perhaps? There are lots of options to choose here, and only the basic stuff is required for the server launch, rest we can add later. This feels like a furniture mod thing, custom models and all. And considering that, I would leave the discussion there.

**Comment by lumberjackgames** [comment]
I support expanding fake fire. I would also like to see colored fires beyond ice fire tied in to the color system @lisacvuk has mentioned with dyes, gems and flowers. It will give the game a nice sense of continuity and be useful for color themes and any sort of guild type gameplay that might evolve later.

Edit: I also agree this should be combined in furniture/decor related 

As a suggestion, color fires might be a result of fire interaction with dye (feed the fire dye) rather than a whole set of new crafts

**Comment by ChandlerBing1994** [comment]
Green, white, purple fire would be cool too

**Comment by bobmacphee** [comment]
I support this suggestion, and as aforementioned some extra colours would definitely be cool.

**Comment by theraven262** [comment]
Here are the exact colours from colouredstonebricks, I would implement these for all the colorization on the server (wool, bricks, dyes) as a reference to the old server. Here are the colour values: 
Black       #1d1d1d
Brown       #43282b
Cyan        #41aab9
Dark Blue   #3d73a3
Dark Green  #40924a
Dark Grey   #626262
Dark Pink   #b73fb3
Green       #4ab12e
Grey        #9d9d9d
Orange      #b76f3f
Pink        #b6767d
Purple      #493da3
Red         #b03f43
White       #b8b8b8
Yellow      #bdb537

**Comment by wrynvera** [comment]
Approved, closing and moving to pending/rewrite (there's more stuff to add than combine) track
