### ISSUE TITLE
[WIP/Concept] For inclusion from Darkage

### ISSUE THREAD

**Issue by lumberjackgames** [Craigs-Crew/edgy-dark-ominous-game#54]
Proposals (discuss below. this list is a starting point):

1. Nodes to keep, update, merge or trash.

#### Keep
- Chalk, reinforced chalk, basalt, 
- ORS, rebrand as other pink mineral
- glass/lighted glass nodes: keep
- Dry leaves, dark dirt: keep for garden/decor
- Mud, integrate into bricks of some sort

#### Retexture
- Lamp keep, multicolor?
- Marble, Serpentine retexture?
- Slate, retexture or trash: current texture is too flat and sticks out in game.

#### Merge
- bars/grilles maybe keep bars, merge with decor/furniture?
- chain: keep/update texture for light/hanging fixtures merge with decor/furniture
- Straw keep/merge with farming ornamental straw

#### Trash
- reinforced wood:  trash
- Box: cut, crates are being added.
- Silt, shale, schist, gneiss, adobe, shelves(redundant) all trash to make room for other color minerals if needed or just cut down nodes that don't add much.

2. Replace legacy mapgen with ore registrations for any kept mapgen nodes.

3. Integrate nodes into variations as needed.

See [issue 22](https://github.com/Craigs-Crew/edgy-dark-ominous-game/issues/22) for earlier discussion on issues with darkage.

**Comment by lumberjackgames** [comment]
I for one would like a straw node and something akin to basalt.

**Comment by ChandlerBing1994** [comment]
Remove the "cobble with plaster" item, and the mud.

**Comment by wrynvera** [comment]
I like to retain the existing veiny marble texture actually.
I'm not against adding more refined forms of marbles with less veiny textures.

**Comment by ChandlerBing1994** [comment]
Keep ORS with the same texture but rename it to something else, maybe "kaihalulu" (famous pink/red beach in hawaii)?

On the veiny marble, I agree with neinwhal. I suggest having two of varieties of it as well, one with a light tint of purple, and another one with a light tint of blue.

Keep mud with its current texture but also maybe have it have some sort of function, perhaps mudbrick? We already had dirt bricks on Craig's so maybe we could just add mud into an alternate recipe for it.

Slate: Keep, although I'm not a fan of those lines that go across it, definitely remove or retexture those.

Silt, shale, schist, gneiss, adobe, shelves - definitely trash.

**Comment by theraven262** [comment]
I disagree with trashing reinforced chalk, it is really good for making medieval builds.
Mud might be fun to make into bricks/tiles.
Slate texture doesn't even tile properly, and the bricks are very poorly made (they have no shading), so I agree with retexturing.
We already have a dark green coloured node (malachite) so I don't think jade would work out, hard to make them that much different, but the serpentine could still work out if I manage to make a proper texture for it.
I support multicolored lamps, and agree with trashing the rest of the nodes marked for trashing.

**Comment by lumberjackgames** [comment]
I have updated and sorted the lead comment to reflect feedback so far. If we can focus on settling into approval on the keep/retexture items, I will work on getting the nodes in the game with their ore gen code to get us a step closer to a usable map. 

This should not stop discussion and exploration of updated textures or variations of nodes.

**Comment by lumberjackgames** [comment]
> serpentine could still work out if I manage to make a proper texture for it.

Personally, I think I would like a rather simple texture in this case. Something like an lighter earthy green sandstone would fill nice gap in the current palette of building materials in my opinion.

**Comment by wrynvera** [comment]
#79

**Comment by lumberjackgames** [comment]
I'm working on the pending parts of this WIP that haven't been already done by Raven (Thanks!) in the upcoming days. Just posting a quick summary of what I plan to do to make sure we are all on the same page:

- Add ORS node. Rebrand as mineral salt (search images of Himilayan salt caves) if everyone is okay with that. Ore gen can be up for discussion but I will stick something similar to ORS previous spawning in for now that we can adjust later. This will probably need a texture update to fit into variations.

- Add bar nodes. We can discuss how these will be crafted.

- Add chains for decorative/climbing purposes. Again, crafting is up for discussion.

- Add basic darkage lamp. We can explore expanding to different color/shape options in future update.

- Add straw node for building material with stair/slope support. We can discuss crafting or integration with flora/farming related mods.

If I missed anything or there are any suggestions please comment. Thanks!

**Comment by lumberjackgames** [comment]
All items have been added with the exception of the lamp which will be handled separately.
