### ISSUE TITLE
[Concept] Horticulture & flora

### ISSUE THREAD

**Issue by wrynvera** [Craigs-Crew/edgy-dark-ominous-game#63]
This idea is concerned with flowers, farming and an expansion of flora decorative nodes.
In that regard, it's a continuation of #15 but also an expansion, in particular, providing more decorative flora and blocks.

This concept is very early in its planning stages, and I'm putting this out to gather more ideas. While I have a general idea of how approaches should be taken, nothing here is concrete yet.

Horticulture focus on farming on a small scale as compared to agriculture and is concerned with small-scale food crops, medicinal plants and ornamental plants.

The primary difference is that horticulture provides more attention and care to the plants grown rather than mass intensive & large-scale crop production.
With that in mind, this change converts the farming mod into one that focuses more on quality than quantity, little amount crops will produce high yield when given the right conditions.
In that aspect, the adoption of this idea allows the following benefits;

1. Lag reduction (Small-scale farming)
2. More complex and less repetitive systems (and potentially fun)

In particular, I'm interested in the following areas of horticulture to adapt and implement.

- Greenhouse systems
- Olericulture (Production of vegetables)
- Floriculture (Production of ornamental plants)
- Hydroponics (Growing plants without soil)

Crops to implement:
Herb in mt context means granting temporary effects.

(* = difficulty)
- Wheat * (straw production)
- Flax * (linen production)
- Cotton ** (wool production)
- Potato ** (Only proper food source)
- Flowers ** (as currently present in mtg) (Dye, decoration and herbs)
- Cactus * (fuel - expansion on fuel idea; potential for refinement to get better fuel)
- Papyrus * (paper)
- Lotus ** (Dye and decoration, herb) - upgrade from existing lilypads
- Mushrooms ** (decoration, herb)
- Moonflower *** (decoration, herb) - For those of you that remembered, for a while, it was debated whether this was to be added in mtg, its a unique idea I think can be built upon here, moonflower will exist as a valuable commodity, it is the equivalent of finding mithril while mining for explorers.
- Vines ** (Dye and decoration, herb)

Limitation of large-scale farming through difficulty in requirements.
Making setting up farm something much more than just tilting the dirt.

- Requirement of compost instead of simple soil, planting pots instead of the ground
- More complex forms of hydration than a simple water source block
- Greenhouse structures or machines (A potential late-game progression, that will vastly increase the yield of crops)

Code implementation

- Nodetimer as a base
- LBM to re-enable node timers on unexpected server crashes

**Comment by wrynvera** [comment]
#### Main Goal
To add a sense of progression to the entire farming system, and allow small farms to reach high yields (up till x15), while providing more costs to farming, to limit players to build "tall" farms rather than "wide" farms.
#### Side Note
While I didn't add the purpose of the crops here, because I'm still thinking about it, each crop will have an important purpose, whether it be building blocks, deco, fuel or crafting materials, they will contribute to buildings / the crafting system rather than serving as food.
#### Experiment.
This entire concept is experimental at best. I'm not expecting full adoption of the idea, but rather I'm expecting more ideas and/or concerns.

### Components:
1. Planter-box
Crops will now require planter boxes to be planted, compared to the simple method of ploughing the ground.
The most rationale for this is to increase the cost of farming, so as to decrease the number of crops growing at once, hence decreasing lag.
Planter boxes require growing medium; which presently comes in 3 forms.
    * Clay (Most basic, normal growth)
    * Compost (Requires a composter to make, convert high amounts of natural matter into low amounts of compost, slight buff)
    * Foam (Moderate-expensive recipe, haven't decided upon its cost, moderate buff)

2. Artificial Lighting
Lighting is the first upgrade that can be made. These lighting are made with mese lamp.
Crop growth are still affected by light, applying these lightings will negate that and ensure its always under optimal light.
Additionally, there's an option to intensify these lights, making them consume fuel but increasing the speed of the growth.

3. Auto-Planter Box
This is an upgrade from the normal planter box and is a lot more expensive to craft.
Likewise, it requires a growing medium.
But unlike, the normal planter box, it slowly converts the growing medium into useless dirt.
In return, however, the planter box will auto-harvest & auto-replant the plant.
Artificial Lighting and growing medium buffs still apply accordingly.

4. Coldframe (Mini-greenhouse)
A coldframe is essentially a combination of the auto-planter box and artificial lighting. While also providing an additional buff.
This is achievable only in the lategame as it will require expensive resources and complex recipes.
There are 4 stages of upgrades before it reaches its full potential.
    * Stage 1: Functions like an auto-planter box + artificial lighting together, consumes planting medium + fuel.
    * Stage 2: The cost of planting medium is negated, fuel must still be provided.
    * Stage 3: Fuel must still be provided but when mese is provided a massive buff is granted.
    * Stage 4: Machine runs purely on mese, consistent massive buff.

The cost of operating and constructing this will be incredibly high as well, but the yield will be incredibly high as well.
This is simply to provide an easy way to get high quantity of farming materials for lategame players that have the resources to maintain it.

### Special crop growth stages
Much like current farming, crops grow in stages.
However, what is new is the addition of special stages, this is what i mean when i mention "buffs" previously.
These special stages are unlocked based on the growing medium/artificial lighting etc.
When better growing medium is provided, and/or artificial lighting is powered/provided, the plant can grow into additional stages, which will give a much higher yield when harvested.

### Regarding seeds, yield and harvest.
There will be methods of harvesting crops in their plant form as well, this will allow replanting of them to create large purely-decorative farms, as per possible now, but without the hindrance of the massive amount of timers running.
Players will be rewarded with high yield when using more complex methods to maintain their farm.
In return, seeds are no longer a guaranteed item, rather comes at a very very low chance (<3-5%), because there is no longer a need to have a lot of crops to produce a lot of produce.
Exploring is another method of getting them, but since mapgen is still under uncertainly, I won't touch on this yet.

### Different forms of farming
The methods I have stated above are the general methods of farming normal crops, there are special crops that are farmed differently, the methods of which I haven't fully decided yet, but will be built onto the existing framework I described above.
- Normal: Wheat, Cotton, Potato, Flowers (These crops are within 1-2 height and grow using normal systems as stated above).
- Pond: Lotus, Moonflower, Papyrus (These crops requires a different water-ish medium to grow, but otherwise function mostly the same as normal)
- Vines: (These crops require trellis frames to grow on, but otherwise function the same as normal)
- Mushrooms: (These crops require darkness to grow instead of light, there will be special forms of artificial lights to grow them, as well as ones that are necessary to grow specific breeds, glowing etc)
- Cactus: Cactus will require a very special framework that is built on top of the existing one; I intend to extend cactus' purpose as fuel, and building upon it further, particularly, the ability to produce and/or refine better fuel from cactus - I haven't fully decided on this yet, but it will be something special.
- Crystal: A potential expensive addition, my recent additions saw uses of mese as fuel, this is potentially a way to make renewable mese, albeit at low amounts and high operating costs. Potentially an expensive growing medium + artificial light with high fuel consumption.

**Comment by theraven262** [comment]
I really like this idea, because it adds a lot of gameplay value, and that will make more people stick with the server.
After reading your ideas, a thought that came to my mind was that we should perhaps explore the paths that would lead to more interconnection between different modules of the game. For example: for mushrooms, you could add a certain gem to the growing process to make the result grow into a glowing mushroom of that gem's color. Glowing vines would be really nice for building if done correctly (does the whole vine glow or just some gems embedded into it do?).

Apart from that, I see that we will require a lot of graphics made, so ya know, tell me if anything needs doing.

**Comment by wrynvera** [comment]
This post goes into more detail into different types of growing medium, planterbox and artificial lighting.

### Growing Mediums
Divided into 3 types for now, ground (for normal crops), water (for pond-based crops), fungi (for fungus crops)
#### Tier 1 (Default)
- Clay (Ground)
- Tree (Fungi)
- Wet Clay (Water)
#### Tier 2 (Boost: +1 stage)
- Compost (Ground / Fungi)
- Mud (Water)
#### Tier 3 (Boost: +2 stage)
- Foam (Ground / Water / Fungi)

### Planterbox Types (Consist of auto-planters as well)
Planters will have 2 inventory slots, 1 for growing medium, the other for a water bucket. Once both conditions are fulfilled, the respective seeds can then be placed.
- Normal (Typical plant, plant grows upwards)
- Hanging (Vines-based plants, plant grows downwards)

### Artificial Lighting Types
When powered with fuel, these lightings also provides a boost of +1 stage.
- Mese lights (Provides high-intensity light - for most typical plants)
- Amethyst/Garnet (Provides low-intensity light - for most fungi and some specific plants)
- UV (Provides UV light - for glowing fungi and some specific plants)

### Concerning coldframe
By default, coldframes will always provide a boost of +3 stage (tier 3 growing medium + powered lighting)
Coldframes will have to be equipped with an artificial lighting panel and powered with fuel constantly.

**Comment by lumberjackgames** [comment]
Looks good. i like the integrations with the minerals!

**Comment by wrynvera** [comment]
Issue discussion transferred to discord for consistency
