### ISSUE TITLE
Workbench rewrite

### ISSUE THREAD

**Issue by wrynvera** [Craigs-Crew/edgy-dark-ominous-game#64]
See >>> https://github.com/Craigs-Crew/edgy-dark-ominous-game/issues/64#issuecomment-993084221

Outdated;
> This is an open discussion for refinements to be made further.
>
> Improvements:
> - ~~Accessing workbench tabs through the workstations themselves~~
> - [ ] Ability for shapes cutter to convert any shapes into workable material (Rather than the need to craft them into cubes first)
> - ~~Furnaces are portable, but can be linked to workbenches~~
> - [ ] Create a portable shapes cutter (handheld circular saw)
>
> Fixes:
> - [x] Ensure there's at least 2 node tall space clearance before placement

**Comment by wrynvera** [comment]
I will cut "Accessing workbench tabs through the workstations themselves" for the shapes completely.
I realize through the way I coded it, all the shapes formspec are linked to each other, so there's no way to detach them accordingly without massive restructure and rewriting, and it's not something I'm keen to do.

For the furnace, however, it is possible to be split, with some changes here and there, so I can provide that.

I'll provide a portable "handheld circular saw" instead for remote access instead, it must be linked with a workbench you own and since it accesses the workbench meta directly, where the workbench and its stations be must be loaded accordingly for it to work.

**Comment by wrynvera** [comment]
Will scratch anything that involves rewiring existing mechanics.
There's simply too much interface linked together, at that rate, im essentially rewriting parts of the mod again.

I'm looking instead to expose certain elements, to allow remote access of existing elements.

**Comment by wrynvera** [comment]
Scratch everything again.
I'll be redo-ing workbench in its entirely.
I want to rid of the old circular saw UI, which isnt the most efficient nor neat way to display things.

The rewrite will retain all existing features, with the goal of isolating all workstations as well.
Workbench will serve as a consolidating structure, no longer as a requirement.
I intend for easy ways to mass register new forms of recipes as well.
In general, the idea is to make everything much more modular than the entangled state it is currently in.

Ill place this a bit behind on the backburner though, will finish up morechests/crates first before embarking on this, together with farming.

**Comment by wrynvera** [comment]
If there's anymore concerns, please state now.
These are what i will be addressing in this rewrite;
- Ability to recycle any variation into their original counterpart (raven)
- Making each station more independent (lumber)

I likely won't be doing another rewrite.

**Comment by lumberjackgames** [comment]
Modularity and recycling sounds good. That will resolve my concerns about restricting workflows. Not sure if that means there will be additional portable versions of stations or not now but i assume those would not be needed now, right?

**Comment by wrynvera** [comment]
Generally, workstations will be portable by default.

Additionally, previously the reason why the cubic section was split into 2 was because it was too *untidy if they were fitted into 1 with the existing UI, after the redo of the UI, I should be able to cramp everything into the sawtable, and still make everything neat;
Making the sawtable the access point for all cubic nodes.
And the CNC, for all non-cubic.
Both will still require fuel, to counter that, very simple existing shapes like stairs and slabs will retain their crafting recipes.

I do like the idea of a remote way of accessing the shapes interface though, so I'll keep certain things exposed such that that is possible. But I'll likely do that after as an enhancement than involve such things in the initial rewrite.

I'm leaning towards a button format for everything as well.
Furnace, im certainly switching to a button format, the current way its handled is a bit hacky I admit.
Circular_saw, there are benefits to, namely, it will completely reduce the need to have micro-nodes, since everything will be crafted in their whole, there's nothing leftover.
With the ability to recycle anything back into nodes as well, there's no risk of crafting more than is needed, simply put it back into the workstation and reconvert it back.

From a UI perspective, a button format is better as well, as its easier to modify, both visually and technicality.
But ill reconsider this again when im actually crafting it.

If i do use the button format however, once there's a basic workable version, ill open it for testing, to see how everyone feels about this change.

**Comment by wrynvera** [comment]
I will be providing fixed methods of crafting rather than allowing fully custom methods, this is to simplify the API.
3 main types of crafting will be provided;
Custom crafting using various types below will be supported, each crafting recipe will take into account two factors, type & category, type is one of the 3 as stated below, category is a fully custom grouping field.
Custom fuel will be supported as well, as per currently.
If there's any request for more custom crafting methods, do state.

1. Crafting
   - Support up till 5x5 grid, 4 ouput
   - Multiple input > Singular output

2. Variation (circular_saw-like)
   - Few input > Multiple (singular) output (Support up till 4 input, unlimited output)

3. Cooking
   - Few input > Few (different) output (Support up till 9 input, 9 output)
   - (might consider supporting time, depends on how much work it is to add it, otherwise, will be moving time support into a future enhancement)

**Comment by wrynvera** [comment]
I think my code direction of workbench has changed too much for this thread to be relevant. I will start a new one with a pull when it's in a presentable state.
