### ISSUE TITLE
[Concept] Advanced chest (morechests & more)

### ISSUE THREAD

**Issue by wrynvera** [Craigs-Crew/edgy-dark-ominous-game#69]
This proposes to combine functions of morechests into a single storage node.
Much like I have done with signs;
There will be a lock icon within chests to determine whether the chest is locked/protect-locked/dropbox/mailbox.
The shared field is integrated in as well, if the chest is locked/protect-locked/mailbox, the shared field will be considered.

I would like to add QOL improvements as well.
Some things that I have in mind are:
- Labelling chests
- Sorting functions (auto-sort and moving entire rows)
- Trash slot
- Portability (ability to pick up) (Unconfirmed, will have to consider technicalities)

Visual-wise, I'm still deciding what the chest should look like, any suggestions in this department is appreciated as well.
For now, im leaning towards a simple cabinet-like design (ikea eket) or a cardboard box-like.

Opening the floor for any other suggestions to add as well.
But anything entity-involved is out of the question, such as equipping the chest with an itemframe-like function; unless you have an idea how to approach it with other means.

**Comment by lumberjackgames** [comment]
Everything sounds good. I like the lock mechanic. Simple wood/material cabinets would be great or just an improved chest with a bit better texture is okay with me too. Cardboard box might be sort of bland or unattractive imo. Crates are cool.

**Comment by ChandlerBing1994** [comment]
Very good! Though I think the chests should stay the same as the default with some minor visual improvements. an IKEA EKET is a bit much, and a cardboard box is too bland and unattractive as lumber said.

**Comment by wrynvera** [comment]
I like the idea of crates, i was trying to think of a node that looks visually simple yet complex to be interesting enough, i think crates fill the category just nice.

**Comment by theraven262** [comment]
I like this idea very much, yes
