### ISSUE TITLE
Combining stairs, fences, panes, columbia and moreblocks into a mega circular saw mod

### ISSUE THREAD

**Issue by wrynvera** [Craigs-Crew/edgy-dark-ominous-game#7]
The proposal is as per the title.
Combining various iterations of block modifications into a single crafting unit.
It allow much easy access to all the variations and the ease of making those nodes as well.

These variations can then be deconstructed in your crafting grid to the macroblocks, where you can combine them to get a full block again, much like my changes to moreblocks on craig's server.

This is any early example incorporating fences and panes
![Capture](https://user-images.githubusercontent.com/3191240/143249297-d15e1a0c-a5e9-41aa-9795-83b3a1d4f893.png)

But as lisac suggested, tabs would be helpful in organization, and i agree.
So the circular saw will be split for now, into 4 tabs;
moreblocks; slopes; fences/walls/panes; columbia

**Comment by ChandlerBing1994** [comment]
Agreed. The circular saw itself should also probably be replaced with a workshop block and be renamed.

**Comment by lisacvuk** [comment]
Add a tab for furniture I think

**Comment by wrynvera** [comment]
> Add a tab for furniture I think

For further tabs, i think its too soon to decide, because there is nothing concrete there yet.
Ill work with what we already have first.
But future additions should be easy, just a matter of modifying the formspec accordingly.

Also, can i take that as an approval? So i can close this and move it to WIP

**Comment by lisacvuk** [comment]
Yup, you can merge the current stuff. We'll deal with the furniture later

**Comment by wrynvera** [comment]
Closing. Will reopen as a pull with the appropriate code and more explaination.
