### ISSUE TITLE
[Discussion] Restyle of slopes shapes

### ISSUE THREAD

**Issue by wrynvera** [Craigs-Crew/edgy-dark-ominous-game#73]
Slopes have been something that has been differing in style, which when used incorrectly, result in certain structures that don't fit in style with the rest of the cubic world. Since homedecor is being redone to fit the style, I thought I'll apply the concept to slopes as well.
This proposes two potential solutions to remedy it, both of which does come with their drawbacks.
This is more of a discussion and experimental change rather than a proposal.

1. Re-UV to fit the pixel grid
One of the main reasons why slopes tend to look out of place is the result of their stretched textures, potentially all the slopes models could be redone, such that the slanted surfaces still match the pixel grid rather than stretch it.
      1. [ Issues ] How do those new larger textures fit? Are we providing a brand new texture for every stretched texture surface or simply tiling it and cutting the excess, which may not look too well for certain textures. If the prior, it is extra work to add more textures per node & these extra textures will result in extra load-time as well.
      2. [ Potential ] This approach is a fair compromise between both sides, we get the keep the lower polygon count while at the same time providing something that fits into the style better.

2. Change the slopes back to cubic style
This entirely redo the slopes with microcubes.
      1. [ Issues ] This uses significantly higher polygon count, copious usage of such nodes might cause some noticeable hamper to performance. Though this is still better than the earlier implementation of moreblocks with nodeboxes, since meshnodes will still allow lower polygon count. Potentially, there's no need to use all 16 pixels as well, might be worth experimenting with 8 or 4 that could provide a significant enough sloping effect, with lower polygon counts
      2. [ Potential ] This fits within the cubic style perfectly, there's no major work that needs to be redone in the texture department as well, the normal textures can still be projected normally the slope faces, the only issue comes when dealing with nodes that have different texture faces, but that is rare, since most stair textures use a uniform texture throughout.

I'm quite interested to experiment with (1), it doesn't require that significant of a rework, and I believe does provide significant consistency with the rest of the environment, at a cost of the loadtime, which frankly, considering we are keeping the majority of the shapes, is something we are already dealing with, and more visual consistency at the cost of a little extra loadtime is fine by me.

**Comment by theraven262** [comment]
I don't think the voxel approximation of the slopes is worth it. I think this could be handled with uv, if we agree on changing this, as people might point out that the sloped texture already neatly fits the sides

**Comment by lumberjackgames** [comment]
As I don't really have technical expertise in this area, my only real opinion is I prefer to not increase polygons. I'm not particularly keen on adding to load time anymore than we have to either, but if it really looks that much better, it would probably be worth tradeoff.

**Comment by wrynvera** [comment]
I think I will close this issue. Raven is right that `people might point out that the sloped texture already neatly fits the sides`, something I didn't consider.
I think stretched tiling is still better than voxel approximation unmatched tiling.
There might be other ways to get both, but nothing comes to mind as of date - I will reopen this if anything comes to mind - OR anyone can do so too.
