### ISSUE TITLE
Rewrite 3D_Armor

### ISSUE THREAD

**Issue by lisacvuk** [Craigs-Crew/edgy-dark-ominous-game#8]
This mod served (in my opinion) a mostly decorative purpose - without mobs, only fall damage was a concern. I do like using it decoratively, but it's performance impact should be investigated.

**Comment by wrynvera** [comment]
I think there's a possibility to explore this further.
We don't have a need for pve or pvp since we are a building server..
But..

Mobility improvement might be something that can be useful for building.
My proposal is to rewrite armour into something that provides better mobility rather than extra protection, or extra protection in some cases (fall protection)

**Comment by lisacvuk** [comment]
Idea: Remove damage completely, make better armors allow players to run faster, perhaps carry more (and consider some additional benefits)

**Comment by ChandlerBing1994** [comment]
Disagree with removing damage completely, sort of defeats the point of survival. There could however be an armorset that reduces damage by 90%.

EDIT: Changed my mind.

**Comment by lisacvuk** [comment]
I don't feel damage was an important part of Craigs, and I'm not sure we should be aiming to make it one. Here is my reasoning:  
- The only way to take damage was to either fall, or drown, or get hit by other players.  
- As there was (realistically) no PvP, this only leaves falling and drowning  
- Both of these were just annoying
  
Furthermore, pretty much all of the servers regulars had admin armor and weren't affected by it in the first place.  
Craigs server was 'Survival' in a sense that resources had to be gathered, the opposite being 'Creative'. I don't see damage being that to that in any meaningful way.

**Comment by lumberjackgames** [comment]
I agree that we should disable pvp. I don't care if armor is included as some sort of buff mechanism or decoration only, but I don't consider this a survival game. Just not a creative building game so definitely let's disable anything that could impact performance.

**Comment by ChandlerBing1994** [comment]
Hm, fair enough. I agree then.

**Comment by lumberjackgames** [comment]
> I think there's a possibility to explore this further. We don't have a need for pve or pvp since we are a building server.. But..
> 
> Mobility improvement might be something that can be useful for building. My proposal is to rewrite armour into something that provides better mobility rather than extra protection, or extra protection in some cases (fall protection)

I do like the idea of unlock privs with armor instead of a subjective/administrative process for gaining fast/fly type privs that enhance building ability. Gives a good reason to mine and deal in ingots as well. I would +1 this implementation.

**Comment by bobmacphee** [comment]
I definitely approve of armour, even if it's only decorative. Players like it because it looks fancy! I definitely think that it should provide varying degrees of protection against damage, even if just from falling/drowning. 
Admin armour should definitely be provided for admins as it makes it easier for new players to tell if someone is actually who they say they are.

**Comment by wrynvera** [comment]
I think the general consensus here is that we should keep and rewrite armour.
In that aspect, I think there's already 4 approvals for it. Me, @lumberjackgames @ChandlerBing1994 @bobmacphee 
Correct me if I'm reading it wrongly, but if there are no further responses to this, i will consider it as a pass and move armours to rewrite.

The specific concept of how and what, can be discussed again when there is someone working on it.

**Comment by ChandlerBing1994** [comment]
Yup.

**Comment by wrynvera** [comment]
Right, no other comment for a day, ill close this and move to rewrite/pending track.
If anyone has anything to add to it, feel free to reopen.
