### ISSUE TITLE
Variations for bricks and tiles

### ISSUE THREAD

**Issue by wrynvera** [Craigs-Crew/edgy-dark-ominous-game#9]
From raven:
I had this feature idea, make multiple types of bricks/tiles for each material block (crafting value 1 to 1), and all of them to be "3D" as this mod does https://forum.minetest.net/viewtopic.php?t=11179&p=176555
Also remove crafting for these and make them craftable in the circular saw

_Originally posted by @theraven262 in https://github.com/Craigs-Crew/edgy-dark-ominous-game/issues/2#issuecomment-977891918_

**Comment by lisacvuk** [comment]
Support, so long as they aren't polluting the craft guide. There should be a unified mechanism for crafting these.  
  
>  Also remove crafting for these and make them craftable in the circular saw  
  
Support.

**Comment by wrynvera** [comment]
support as well, but totally agree with lisac.

**Comment by ChandlerBing1994** [comment]
Support, as per Lisac.

**Comment by theraven262** [comment]
I finished making the textures for nine different tile types for the default materials (stone, desertstone, desert sandstone, sandstone, silver sandstone and obsidian). Regarding the implementation, I think it would be best to store these variations on a per materials basis as a spritesheet of 3x3 node textures.

**Comment by wrynvera** [comment]
I think this has pretty much been approved.
@theraven262 I will keep the thread up so you can have some place open further discussions if there's a need to.

**Comment by theraven262** [comment]
I'm looking for ideas on what other materials in the base game should have bricks/tiles, such as ice or dirt(maybe?)

**Comment by ChandlerBing1994** [comment]
Ice, dirt, coral skeleton (maybe), obsidian, silver sand stone.

**Comment by wrynvera** [comment]
Not sure if you have heard of the chisel mod from Minecraft. It does something similar, providing a wide variety of the same tiles, might be worth taking a look at that and its textures for inspiration.

**Comment by theraven262** [comment]
Yeah I think that all the metal blocks should have the tiles then. The default materials, as I have said, are already done. Just need to be implemented in the code.
I checked out the chisel mod and I don't think we can allow for as many tile variations to be implemented as already we are working with at least 10 (counting in the base) nodes per material. Of course add to that all the furniture types (the number of which we haven't yet settled upon) to each material as well, its a lot.
